name: OpenSearch Dashboards Functional Test Template

on:
  workflow_call:
    inputs:
      endpoint:
        required: true
        type: string
    secrets:
      osd-user:
        required: true
      osd-user-password:
        required: true

jobs:
  OSD-Functional-Test-OSD:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout functional test repo
          uses: actions/checkout@v3
          with:
            repository: elastic-analytics/opensearch-dashboards-functional-test
            ref: playground-preview

        - name: Step 0 - Install dependencies for functional test
          run: |
            npm install
            npm install -g yarn

        - name: Step 1 - Check If OSD is Up
          run: |
            sleep 30s
            curl -XGET --retry 15 --retry-delay 30 --retry-all-errors -k -u '${{secrets.osd-user}}:${{secrets.osd-user-password}}' '${{inputs.endpoint}}/api/status' > $HOME/osd-response.json
            echo "OSD_STATUS=$(cat $HOME/osd-response.json | jq -r '.status.overall.state')" >> $GITHUB_ENV

        - name: Step 2 - Run Functional Test For OSD
          if: ${{ env.OSD_STATUS == 'green'}}
          run: |
            yarn cypress run --spec "cypress/integration/playground/dashboards/*.js" --config "baseUrl=${{inputs.endpoint}}" --env "openSearchUrl=${{inputs.endpoint}},SECURITY_ENABLED=true,username=${{secrets.osd-user}},password=${{secrets.osd-user-password}}"

        - name: Step 3 - Add moviegeek dashboard
          run: |
            curl -XPOST ${{inputs.endpoint}}/api/saved_objects/_import -H 'osd-xsrf: true' --form file=@cypress/dashboards/moviegeekdashboard.ndjson -k -u ${{secrets.osd-user}}:${{secrets.osd-user-password}}

        - name: Step 4 - Add metricsbeat dashboard
          run: |
            curl -XPOST ${{inputs.endpoint}}/api/saved_objects/_import -H 'osd-xsrf: true' --form file=@cypress/dashboards/metricbeat-eks-overview.ndjson -k -u ${{secrets.osd-user}}:${{secrets.osd-user-password}}

        - name: Step 5 - Add introduction dashboard
          run: |
            curl -XPOST ${{inputs.endpoint}}/api/saved_objects/_import -H 'osd-xsrf: true' --form file=@cypress/dashboards/introduction-dashboard-observability.ndjson -k -u ${{secrets.osd-user}}:${{secrets.osd-user-password}}

        - name: Step 6 - Add Nginx dashboard
          run: |
            curl -XPOST ${{inputs.endpoint}}/api/saved_objects/_import?overwrite=true -H 'osd-xsrf: true' --form file=@cypress/dashboards/NGINX-Core-Logs.ndjson -k -u ${{secrets.osd-user}}:${{secrets.osd-user-password}}

  Plugins:
    runs-on: ubuntu-latest
    needs: OSD-Functional-Test-OSD
    strategy:
      fail-fast: false
      matrix:
        run: ['OSD-Functional-Test-AD', 'OSD-Functional-Test-Alert', 'OSD-Functional-Test-Notifications', 'OSD-Functional-Test-Reports', 'OSD-Functional-Test-Observability', 'OSD-Functional-Test-IndexMan']
    steps:
    - run: echo Run ${{ matrix.run }}
    - name: Checkout functional test repo
      uses: actions/checkout@v3
      with:
        repository: elastic-analytics/opensearch-dashboards-functional-test
        ref: playground-preview
    - name: Install dependencies for functional test
      run: |
        npm install
        npm install -g yarn
    - name: Run Functional Test For AD
      if:  ${{ matrix.run == 'OSD-Functional-Test-AD' }}
      run: |
        yarn cypress run --spec "cypress/integration/playground/plugins/playground_ad*.js" --config "baseUrl=${{inputs.endpoint}}" --env "openSearchUrl=${{inputs.endpoint}},SECURITY_ENABLED=true,username=${{secrets.osd-user}},password=${{secrets.osd-user-password}}"

    - name: Run Functional Test For Alert
      if:  ${{ matrix.run == 'OSD-Functional-Test-Alert' }}
      run: |
        yarn cypress run --spec "cypress/integration/playground/plugins/playground_alert*.js" --config "baseUrl=${{inputs.endpoint}}" --env "openSearchUrl=${{inputs.endpoint}},SECURITY_ENABLED=true,username=${{secrets.osd-user}},password=${{secrets.osd-user-password}}"

    - name: Run Functional Test For Notifications
      if:  ${{ matrix.run == 'OSD-Functional-Test-Notifications' }}
      run: |
        yarn cypress run --spec "cypress/integration/playground/plugins/playground_notifications*.js" --config "baseUrl=${{inputs.endpoint}}" --env "openSearchUrl=${{inputs.endpoint}},SECURITY_ENABLED=true,username=${{secrets.osd-user}},password=${{secrets.osd-user-password}}"

    - name: Run Functional Test For Reports
      if:  ${{ matrix.run == 'OSD-Functional-Test-Reports' }}
      run: |
        yarn cypress run --spec "cypress/integration/playground/plugins/playground_reports*.js" --config "baseUrl=${{inputs.endpoint}}" --env "openSearchUrl=${{inputs.endpoint}},SECURITY_ENABLED=true,username=${{secrets.osd-user}},password=${{secrets.osd-user-password}}"

    - name: Run Functional Test For Observability
      if:  ${{ matrix.run == 'OSD-Functional-Test-Observability' }}
      run: |
        yarn cypress run --spec "cypress/integration/playground/plugins/playground_observability_cluster.js" --config "baseUrl=${{inputs.endpoint}}" --env "openSearchUrl=${{inputs.endpoint}},SECURITY_ENABLED=true,username=${{secrets.osd-user}},password=${{secrets.osd-user-password}}"

    - name: Run Functional Test For Index Management
      if:  ${{ matrix.run == 'OSD-Functional-Test-IndexMan' }}
      run: |
        yarn cypress run --spec "cypress/integration/playground/plugins/playground_index*.js" --config "baseUrl=${{inputs.endpoint}}" --env "openSearchUrl=${{inputs.endpoint}},SECURITY_ENABLED=true,username=${{secrets.osd-user}},password=${{secrets.osd-user-password}}"
